### ISSUE TITLE
[Bug]: Loading the file via Plugin Manager generates a crash

### ISSUE THREAD

**Issue by retched** [retched/ZC-USPSRestful#4]
### USPSr Version

0.1.0 (Current Version)

### ZenCart Version

2.1.x

### PHP Version

PHP 8.x

### What happened? Describe the bug in detail

Trying to install the Module as released, creates a crash. However, copy/pasting the non-encapsulated file works normally.

### Relevant Log Output

```shell
[21-Dec-2024 12:09:30 America/New_York] PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in E:\xampp\htdocs\justuptown\includes\functions\plugin_support.php:64
Stack trace:
#0 E:\xampp\htdocs\justuptown\includes\functions\plugin_support.php(64): in_array('v2.1.0', NULL, false)
#1 E:\xampp\htdocs\justuptown\includes\classes\PluginManager.php(73): plugin_version_check_for_updates(2395, '')
#2 E:\xampp\htdocs\justuptown\includes\classes\ViewBuilders\PluginManagerController.php(49): Zencart\PluginManager\PluginManager->isNewDownloadAvailable(2395, '')
#3 E:\xampp\htdocs\justuptown\includes\classes\ViewBuilders\BaseController.php(37): Zencart\ViewBuilders\PluginManagerController->processDefaultAction()
#4 E:\xampp\htdocs\justuptown\justoffice\plugin_manager.php(101): Zencart\ViewBuilders\BaseController->processRequest()
#5 E:\xampp\htdocs\justuptown\justoffice\index.php(16): require('E:\\xampp\\htdocs...')
#6 {main}
  thrown in E:\xampp\htdocs\justuptown\includes\functions\plugin_support.php on line 64

[21-Dec-2024 12:09:30 America/New_York] Request URI: /justuptown/justoffice/index.php?cmd=plugin_manager&page=1&colKey=USPSRestful, IP address: 127.0.0.1, Language id 1
#0 [internal function]: zen_debug_error_handler()
#1 E:\xampp\htdocs\justuptown\includes\functions\plugin_support.php(58): strcmp()
#2 E:\xampp\htdocs\justuptown\includes\classes\PluginManager.php(73): plugin_version_check_for_updates()
#3 E:\xampp\htdocs\justuptown\includes\classes\ViewBuilders\PluginManagerController.php(49): Zencart\PluginManager\PluginManager->isNewDownloadAvailable()
#4 E:\xampp\htdocs\justuptown\includes\classes\ViewBuilders\BaseController.php(37): Zencart\ViewBuilders\PluginManagerController->processDefaultAction()
#5 E:\xampp\htdocs\justuptown\justoffice\plugin_manager.php(101): Zencart\ViewBuilders\BaseController->processRequest()
#6 E:\xampp\htdocs\justuptown\justoffice\index.php(16): require('E:\\xampp\\htdocs...')
--> PHP Deprecated: strcmp(): Passing null to parameter #1 ($string1) of type string is deprecated in E:\xampp\htdocs\justuptown\includes\functions\plugin_support.php on line 58.
```

**Comment by retched** [comment]
This is caused because ZenCart hasn't validated and approved the file for release. So it tries to ping the ZenCart server, gets nothing, and then ZenCart crashes out. Generating the 500 server error.

A fix has already been deployed by zeroing out the plugin ID in the manifest file for the module so it won't disrupt new downloads. If you have already copied the folder into zc_plugins, a fix is needed by editing the value in the database. This can be done by running the following SQL in your ZenCart Backend:

``` SQL
UPDATE jg1_plugin_control SET zc_contrib_id = '0' WHERE unique_key = 'USPSRestful';
```

**Comment by retched** [comment]
Reversed this fix in a recent patch since the plugin is now live in ZenCart's Plugin system.
